name: Deploy Firebase Functions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Login to Firebase
        run: npm install -g firebase-tools && firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy Firebase Functions
        run: npx firebase-tools deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
