name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase-credentials.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Set Firebase project
        run: firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --alias my-firebase-project --token "$(cat firebase-credentials.json)"

      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-credentials.json && npx firebase-tools deploy --only functions --json
