name: Deploy to Firebase Functions via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download deps
        run: npm install

      - name: Deploy
        run: npx firebase-tools deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
