name: Deploy Cloud Functions
on:
 workflow_dispatch:
 push:
   branches:
     - main
jobs:
 build_and_deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: 16.x
     - name: Build Cloud Functions
       run: npm ci
     - name: Create SA key
       run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
     - name: Deploy Cloud Functions
       run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --project default --json && npx firebase-tools --version